### ISSUE TITLE
When errors are rendered on session form, link to other form pushed out of modal

### ISSUE THREAD

**Issue by jmkaneshiro** [Solomon-T/instock#70]
### Summary
When a user clicks the Login or Signup button on the main page, it opens a modal form. On the Login modal, the user also has a button to open the Signup form. On the Signup modal, the user also has a button to open the Login form.

Currently, when errors are rendered after a failed form submission, the button to the other form get pushed out of the modal.

### Notes
Likely fix is to just add `max-height` and `min-height` to the modal or make it more flexible.

**Comment by Solomon-T** [comment]
Fixed it by simply increasing the height.

**Comment by Solomon-T** [comment]
Fixed it by simply increasing the height.
