### ISSUE TITLE
As a user I should be able to indicate that a product is no longer in stock

### ISSUE THREAD

**Issue by jmkaneshiro** [Solomon-T/instock#71]
### Summary
A user is currently able to confirm that something is in stock by clicking a thumbs up icon. A user should also be able to identify that an item is no longer in stock.

### Technical Notes
The ideal solution here is probably to add some kind of timer that filters out reports based on recency of submission. However, this solution is dependent on having regular data submissions and would likely require us to build a cron job type of system to reload seed data regularly.

The lighter weight solution we prefer for now is for a user to be able to click a thumbs down button that decrements the number of report approvals.

**Comment by jmkaneshiro** [comment]
A user should not be able to click the thumbs down button when the approval counts value is zero.

**Comment by jmkaneshiro** [comment]
Button and styling added in #77

**Comment by Solomon-T** [comment]
Implemented. PR up for review

**Comment by Solomon-T** [comment]
Implemented. PR up for review
