### ISSUE TITLE
Provide user with clearer explanation for how to create report

### ISSUE THREAD

**Issue by jmkaneshiro** [Solomon-T/instock#86]
### Summary
Make it clear that I need to search for the location first in order to add a spot. 

### Technical Notes
Will need to adjust the address bar of the SearchBox `map.js` to include more explanatory language. Will also need to expand the size of that address bare in `map.css`.

Consider whether other instructions are necessary as well.

**Comment by Solomon-T** [comment]
Instructions added but feel free to reword them. It always sounds better worded by you.
